name: Docker build and push
description: Build and push docker image
inputs:
    app:
        description: Project repository app name
        required: true
    tag:
        description: Docker Image tag to push
        required: true
    dockerfile:
        description: Dockerfile path name
        required: true
        default: Dockerfile
    registry:
        description: Docker registry URL
        required: true
    username:
        description: Docker login Username
        required: true
    password:
        description: Docker login Password
        required: true
runs:
    using: composite
    steps:
        -   name: Check if project uses submodules
            shell: sh
            run: ([ -e .gitmodules ]) && echo "gitmodules_exists=true" >> $GITHUB_ENV || echo "gitmodules_exists=false" >> $GITHUB_ENV
        -   name: Checkout GIT Submodules
            shell: sh
            if: env.gitmodules_exists == 'true'
            run: git submodule update --init --recursive

        -   name: Set up Docker Context for Buildx
            id: buildx-context
            shell: sh
            run: |
                docker context create builders
        -   name: Docker Setup Buildx
            uses: docker/setup-buildx-action@v2.0.0
            with:
                version: latest
                endpoint: builders
        -   name: Docker meta
            id: meta
            uses: docker/metadata-action@v4
            with:
                images: ${{ inputs.registry }}/${{ inputs.app }}
                tags: |
                    type=schedule
                    type=ref,event=branch
                    type=ref,event=pr
                    type=semver,pattern={{ version }}
                    type=semver,pattern={{ major }}.{{ minor }}
                    type=semver,pattern={{ major }}
                    type=raw,value=${{ inputs.tag }}
                    type=ref,event=tag
                    type=sha,enable=true,priority=100,prefix=,suffix=,format=long
        -   name: Docker Login
            uses: docker/login-action@v2.0.0
            with:
                registry: ${{ inputs.registry }}
                username: ${{ inputs.username }}
                password: ${{ inputs.password }}
                ecr: false
        -   name: Build and push Docker images
            uses: docker/build-push-action@v3.1.1
            with:
                context: .
                allow: network.host
                network: host
                file: ${{ inputs.dockerfile }}
                push: true
                tags: ${{ steps.meta.outputs.tags }}
