name: Docker build and push
description: Build and push docker image
inputs:
    tags:
        description: Docker Image tags to push
        required: true
    dockerfile:
        description: Dockerfile path name
        required: true
        default: Dockerfile
    build-args:
        description: Docker build args
        required: false
    target:
        description: Dockerfile target name
        required: false
    registry:
        description: Docker registry URL
        required: true
    username:
        description: Docker login Username
        required: true
    password:
        description: Docker login Password
        required: true
runs:
    using: composite
    steps:
        -   name: Set up Docker Context for Buildx
            id: buildx-context
            shell: sh
            run: |
                docker context create builders
        -   name: Docker Setup Buildx
            uses: docker/setup-buildx-action@v2.0.0
            with:
                version: v0.9.1
                endpoint: builders
        -   name: Docker Login
            uses: docker/login-action@v2.0.0
            with:
                registry: ${{ inputs.registry }}
                username: ${{ inputs.username }}
                password: ${{ inputs.password }}
                ecr: false
        -   name: Build and push Docker images
            uses: docker/build-push-action@v3.1.1
            with:
                context: .
                allow: network.host
                target: ${{ inputs.target }}
                network: host
                file: ${{ inputs.dockerfile }}
                push: true
                tags: ${{ inputs.tags }}
                build-args: ${{ inputs.build-args }}
