name: Build and push
on:
    workflow_call:
        inputs:
            app:
                description: Project repository app name
                type: string
                required: true
            tag:
                description: Docker Image tag to push
                type: string
                required: true
            dockerfile:
                description: Dockerfile path name
                type: string
                required: true
                default: Dockerfile
            target:
                description: Dockerfile target name
                type: string
                required: false
jobs:
    build-and-push:
        runs-on: [ self-hosted ]
        steps:
            -   name: Generate Docker image tag
                uses: easir/workflows/actions/generate-tag@103d43cb2557cf9bc517c9087c3e630cce54d21a
                id: tags
                with:
                    head: $default_branch

            -   name: Check if project uses submodules
                shell: sh
                run: ([ -e .gitmodules ]) && echo "gitmodules_exists=true" >> $GITHUB_ENV || echo "gitmodules_exists=false" >> $GITHUB_ENV
            -   name: Checkout GIT Submodules
                shell: sh
                if: env.gitmodules_exists == 'true'
                run: git submodule update --init --recursive

            -   name: Set up Docker Context for Buildx
                id: buildx-context
                shell: sh
                run: |
                    docker context create builders
            -   name: Docker Setup Buildx
                uses: docker/setup-buildx-action@v2.0.0
                with:
                    version: latest
                    endpoint: builders
            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v4
                with:
                    images: ${{ secrets.DOCKER_REGISTRY_URL }}/${{ inputs.app || steps.tags.output.app }}
                    tags: |
                        type=schedule
                        type=ref,event=branch
                        type=ref,event=pr
                        type=semver,pattern={{ version }}
                        type=semver,pattern={{ major }}.{{ minor }}
                        type=semver,pattern={{ major }}
                        type=raw,value=${{ inputs.tag || steps.tags.outputs.tag }}
                        type=ref,event=tag
                        type=sha,enable=true,priority=100,prefix=,suffix=,format=long
            -   name: Docker Login
                uses: docker/login-action@v2.0.0
                with:
                    registry: ${{ secrets.DOCKER_REGISTRY_URL }}
                    username: ${{ inputs.DOCKER_LOGIN }}
                    password: ${{ inputs.DOCKER_REGISTRY_PASSWORD }}
                    ecr: false
            -   name: Build and push Docker images
                uses: docker/build-push-action@v3.1.1
                with:
                    context: .
                    allow: network.host
                    target: ${{ inputs.target }}
                    network: host
                    file: ${{ inputs.dockerfile }}
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
