name: Build base
on:
    workflow_call:
        inputs:
            default_branch:
                description: Projects default branch name
                type: string
                required: false
                default: master
            tag:
                description: Docker Image tag to push
                type: string
                required: false
            dockerfile:
                description: Dockerfile path name
                type: string
                required: false
                default: Dockerfile
            target:
                description: Dockerfile target name
                type: string
                required: false
jobs:
    build-and-push:
        runs-on: [ self-hosted ]
        steps:
            -   name: Generate Docker image tag
                uses: easir/workflows/actions/generate-tag@a8a1f573f108cfa0a1a0ad9747d12d625f858e87
                id: tags
                with:
                    default_branch: ${{ inputs.default_branch }}
            -   name: Docker meta with calculated tag
                id: meta
                uses: docker/metadata-action@v4
                with:
                    images: ${{ secrets.DOCKER_REGISTRY_URL }}/${{ steps.tags.outputs.app }}
                    tags: type=raw,value=${{ inputs.tag }}
            -   name: Build and push Docker image
                uses: easir/workflows/actions/build-and-push@a8a1f573f108cfa0a1a0ad9747d12d625f858e87
                with:
                    tags: ${{ steps.meta.outputs.tags }}
                    registry: ${{ secrets.DOCKER_REGISTRY_URL }}
                    username: ${{ secrets.DOCKER_LOGIN }}
                    password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
