on:
    workflow_call:
        inputs:
            make:
                required: true
                description: GNU Make targets list
                default: ""
                type: string

        secrets:
            token:
                required: true
            docker-reg:
                required: true
            docker-pass:
                required: true
            docker-login:
                required: true
jobs:
    analysis-and-tests:
        name: Analysis and tests
        runs-on: [ self-hosted ]
        env:
            GITHUB_TOKEN: ${{ secrets.token }}
        steps:
            -   uses: actions/checkout@v3

            -   name: Check if project uses submodules
                shell: sh
                run: ([ -e .gitmodules ]) && echo "gitmodules_exists=true" >> $GITHUB_ENV || echo "gitmodules_exists=false" >> $GITHUB_ENV
            -   name: Checkout GIT Submodules
                shell: sh
                if: env.gitmodules_exists == 'true'
                run: git submodule update --init --recursive

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "8.1"
                    extensions: pdo_sqlite
                    coverage: pcov
                env: { runner: self-hosted }

            -   name: Composer Install
                uses: ramsey/composer-install@v2
                with: { composer-options: "--no-progress --no-scripts" }

            -   name: Check if any PHP_CodeSniffer configuration file exists
                shell: sh
                run: ([ -e phpcs.xml.dist ] || [ -e phpcs.xml ]) && echo 'phpcs_exists=true' >> $GITHUB_ENV || echo 'phpcs_exists=false' >> $GITHUB_ENV
            -   name: PHP_CodeSniffer
                shell: sh
                if: env.phpcs_exists == 'true'
                run: composer exec -- phpcs

            -   name: Check if any Psalm configuration file exists
                shell: sh
                run: ([ -e psalm.xml.dist ] || [ -e psalm.xml ]) && echo 'psalm_exists=true' >> $GITHUB_ENV || echo 'psalm_exists=false' >> $GITHUB_ENV
            -   name: Psalm
                shell: sh
                if: env.psalm_exists == 'true'
                run: composer exec -- psalm --long-progress

            -   name: Check if Makefile file exists
                shell: sh
                run: ([ -e Makefile ]) && echo 'make_exists=true' >> $GITHUB_ENV || echo 'make_exists=false' >> $GITHUB_ENV
            -   name: Tests
                shell: sh
                if: env.make_exists == 'true'
                run: make ${{ inputs.make }} -O -k
                env: { APP_ENV: test }

    build-and-push:
        name: Build and push
        needs: analysis-and-tests
        runs-on: [ self-hosted ]
        env:
            GITHUB_TOKEN: ${{ secrets.token }}
        steps:
            -   uses: actions/checkout@v3
            -   name: Generate Docker image tag
                uses: easir/workflows/actions/generate-tag@c75dc560f505532e4d5dedb6f5289f4c9358b741
                id: tags
                with:
                    head: master
            -   name: Build and push Docker image
                uses: easir/workflows/actions/build-and-push@brzuchal
                with:
                    app: ${{ steps.tags.outputs.app }}
                    tag: ${{ steps.tags.outputs.tag }}
                    registry: ${{ secrets.docker-reg }}
                    username: ${{ secrets.docker-login }}
                    password: ${{ secrets.docker-pass }}
